#!/usr/bin/env python3
"""
Inject Verified Facts Hook

Deterministic layer: injects real system facts into context at session start.
Claude MUST use these values instead of generating plausible-looking ones.

Anti-hallucination: CWD, username, date, hostname are verified by the OS,
not generated by the model.
"""

import sys
import os
import getpass
import socket
import platform
from pathlib import Path
from datetime import datetime, timezone


def safe_print(text: str) -> None:
    """Force UTF-8 output."""
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stdout.write(text + "\n")
    sys.stdout.flush()


def get_verified_facts() -> dict:
    """Collect deterministic facts from the OS."""
    facts = {}

    # CWD
    try:
        facts["cwd"] = str(Path.cwd())
    except Exception:
        facts["cwd"] = "UNAVAILABLE"

    # Username
    try:
        facts["username"] = getpass.getuser()
    except Exception:
        try:
            facts["username"] = os.environ.get("USERNAME") or os.environ.get("USER") or "UNAVAILABLE"
        except Exception:
            facts["username"] = "UNAVAILABLE"

    # Hostname
    try:
        facts["hostname"] = socket.gethostname()
    except Exception:
        facts["hostname"] = "UNAVAILABLE"

    # OS
    try:
        facts["os"] = f"{platform.system()} {platform.release()} ({platform.version()})"
    except Exception:
        facts["os"] = "UNAVAILABLE"

    # Python
    try:
        facts["python"] = f"{sys.executable} ({platform.python_version()})"
    except Exception:
        facts["python"] = "UNAVAILABLE"

    # Date/time (local timezone)
    try:
        now = datetime.now(tz=timezone.utc).astimezone()
        facts["datetime"] = now.strftime("%Y-%m-%d %H:%M:%S %Z")
        facts["date"] = now.strftime("%Y-%m-%d")
    except Exception:
        facts["datetime"] = "UNAVAILABLE"
        facts["date"] = "UNAVAILABLE"

    # Home directory
    try:
        facts["home"] = str(Path.home())
    except Exception:
        facts["home"] = "UNAVAILABLE"

    return facts


def main() -> None:
    facts = get_verified_facts()

    lines = [
        "=" * 70,
        "[VERIFIED FACTS] Deterministic System Information",
        "=" * 70,
        f"CWD:      {facts['cwd']}",
        f"Username: {facts['username']}",
        f"Hostname: {facts['hostname']}",
        f"Home:     {facts['home']}",
        f"OS:       {facts['os']}",
        f"Python:   {facts['python']}",
        f"DateTime: {facts['datetime']}",
        "",
        "⚠️  ANTI-HALLUCINATION CONTRACT:",
        "   - Use ONLY the values above for CWD, username, hostname, date.",
        "   - Do NOT generate plausible-looking paths or usernames.",
        "   - If a fact shows UNAVAILABLE — say so explicitly, do not guess.",
        "=" * 70,
    ]

    safe_print("\n".join(lines))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[ERROR] inject-verified-facts.py failed: {e}", file=sys.stderr)
        sys.exit(1)
